"""Event types for the final dynamic multi-agent contract.

Phase 1 uses PARCEL_RELEASE as the sole transition from UNRELEASED to assignment-ready parcels; assignment decisions must not bind TBD parcels to scheduled trips or vehicles.
"""

from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    PARCEL_RELEASE = "PARCEL_RELEASE"
    TRUCK_AVAILABLE = "TRUCK_AVAILABLE"
    TRUCK_DEPARTURE = "TRUCK_DEPARTURE"
    TRUCK_ARRIVE_STOP = "TRUCK_ARRIVE_STOP"
    TRUCK_UNLOAD = "TRUCK_UNLOAD"
    TRUCK_ROUTE_COMPLETE = "TRUCK_ROUTE_COMPLETE"
    BUS_TRIP_DEPARTURE = "BUS_TRIP_DEPARTURE"
    BUS_TRIP_ARRIVAL = "BUS_TRIP_ARRIVAL"
    BUS_TERMINAL_DEPARTURE = "BUS_TERMINAL_DEPARTURE"
    BUS_STATION_ARRIVAL = "BUS_STATION_ARRIVAL"
    PASSENGER_ARRIVAL = "PASSENGER_ARRIVAL"
    BUS_RELOCATION_COMPLETE = "BUS_RELOCATION_COMPLETE"
    STATION_OPERATION = "STATION_OPERATION"
    DRONE_AVAILABLE = "DRONE_AVAILABLE"
    BATTERY_CHARGING_COMPLETE = "BATTERY_CHARGING_COMPLETE"
